parameters:
  vmImage: "macos-10.13"
  platform: "macosx"
  installScript: |
    echo "Skipping Install Step"
  buildScript: |
    echo "Nothing to build"
    exit 1
  testScript: |
    echo "No tests, skipping"
  continueOnError: false
  packageDirectory: "sentry-native"

jobs:
  - job: sentry_native_${{ parameters.platform }}
    displayName: Sentry-Native (${{ parameters.platform }})
    continueOnError: ${{ parameters.continueOnError }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      PACKAGE_DIR: ${{ parameters.packageDirectory }}
      PLATFORM_BUILD_DIR: ${{ parameters.packageDirectory }}/build
    steps:
      - template: prescript-common.yml
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: "current"
          downloadType: "single"
          artifactName: $(ARTIFACT_DIR)
          downloadPath: "."

      - bash: |
          set -eux

          ZIP=./bin/zip.py

          unzip -q ./${ARTIFACT_DIR}/sp-sources.zip
          mv sp-sources "${PACKAGE_DIR}"
        displayName: "Package generated build files"

      - bash: |
          set -eux

          ${{ parameters.installScript }}
        displayName: "Install Dependencies"

      - bash: |
          set -eux

          mkdir -p "${PLATFORM_BUILD_DIR}"
          cd "${PLATFORM_BUILD_DIR}"

          ${{ parameters.buildScript }}
        displayName: "Run Build Script"

      - bash: |
          set -eux

          cd "${PLATFORM_BUILD_DIR}"

          ${{ parameters.testScript }}
        displayName: "Run Tests"
